Lesson 1: Добавлен PostgreSQL, pgAdmin4; Удалены ненужные зависимости
Chelove4ik/fefu_backend_2_3 pull request #1
Opened 2021-09-25 03:32 UTC by Chelove4ik

2021-09-28 15:18 UTC, chrn-feip requested changes

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
>          environment:
1. Обратите внимание на раздел Environment Variables тут https://hub.docker.com/_/postgres. Не хватает обязательной переменной. 
2. Почему не стали объявлять POSTGRES_DB?

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
> +            PGDATA: /data/postgres
Зачем понадобилось задавать кастомный путь для расположения файла БД?

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
> +            - postgres
Зачем понадобилось делать отдельную сеть? Все контейнеры могут работать в одной сети sail.

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
> +            POSTGRES_USER: '${POSTGRES_USER}'
Если вводится новая переменная окружения, то надо её также добавить в .env.example, добавить к коммиту. Можно было использовать вместо POSTGRES_* уже имеющиеся в .env.example DB_*.

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
> +            PGADMIN_CONFIG_SERVER_MODE: 'False'
Это что такое и зачем?

2021-09-28 15:18 UTC, chrn-feip commented on docker-compose.yml
> +            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
То же про новые переменные окружения и .env.example

2021-10-01 17:55 UTC, Chelove4ik commented on docker-compose.yml
>          environment:
1. POSTGRES_PASSWORD? Она же установлена 

2. Я думал что она используется в config/database.php )

2021-10-01 17:58 UTC, Chelove4ik commented on docker-compose.yml
> +            PGADMIN_CONFIG_SERVER_MODE: 'False'
Режим сервера определяет, работаем ли мы на веб-сервере. Сейчас я понял что это нужно убрать.

2021-10-01 19:56 UTC, merged